### ISSUE TITLE
Displaying column as JSON View Cell display mode

### ISSUE THREAD

**Issue by chuprik** [Altinity/clickhouse-grafana#189]
Hello! I'm using your plugin for selecting data from CH and displaying it as a table. And I would like to display one column from selection as JSON View Cell. And I have weird Grafana behavior, it looks like selected column is quoted and Grafana can't parse JSON :)

![image](https://user-images.githubusercontent.com/802946/83334621-6d4e1900-a2b0-11ea-9335-5b9d24299448.png)

![image](https://user-images.githubusercontent.com/802946/83334623-7212cd00-a2b0-11ea-8d28-c19fee8f7b36.png)

![image](https://user-images.githubusercontent.com/802946/83334633-8787f700-a2b0-11ea-9fa1-b5b51e2a7a6c.png)

![image](https://user-images.githubusercontent.com/802946/83334737-40e6cc80-a2b1-11ea-912f-9e80a5bc6721.png)

Do you have any ideas on how to fix that? as I can see, CH returns JSON without escaping via HTTP. It looks like I need to tell somehow Grafana that this field should be processed as "raw".

**Comment by kotchuprik** [comment]
fast stupid fix is here https://github.com/StrongSquirrel/clickhouse-grafana/commit/e62fb02dd2a96ccb5121c6a0507c83d3fe841e00

**Comment by Slach** [comment]
@kotchuprik big thanks for a workaround

unfortunately, I don't have any idea how to properly recognize when we shall use JSON.parse and when is not

cause ClickHouse database doesn't have data types like JSON / JSONB in PostgreSQL and Datasource plugin doesn't know anything about visualization method

**Comment by kotchuprik** [comment]
@Slach I had idea do one more update my code and replace string checking with:
```
try {
    r.push(JSON.parse(v));
} catch(e) {
    r.push(v);
}
```

but it looks weird :)

**Comment by Slach** [comment]
@kotchuprik yep, but this solution will decrease performance when data amount will grow

**Comment by kotchuprik** [comment]
maybe it can be handled on golang side somehow?

**Comment by Slach** [comment]
no, golang part of plugin use only for alerts
maybe it can be handled by the "Transform" feature on grafana on the browser side?
https://grafana.com/blog/2020/06/11/new-in-grafana-7.0-data-transformations-for-all-visualizations-that-support-queries/

**Comment by Slach** [comment]
@kotchuprik please subscribe to https://github.com/ClickHouse/ClickHouse/pull/7426

**Comment by Slach** [comment]
@lunaticusgreen add PR with link to this issue

**Comment by Lincyaw** [comment]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/d8e4b0c9-375a-49c6-9c00-7d68cf04a195">


I query the clickhouse, and the ResourceAttributes is the a Map. After querying, this column is regarded as a line rather than a label. What should I do ?

<img width="1416" alt="image" src="https://github.com/user-attachments/assets/5a524c99-4a78-41e2-9adc-8eb8512c1d87">

**Comment by Slach** [comment]
@Lincyaw which type do you have in 
`SELECT toTypeName(ResourceAttributes) FROM default.otel_metrics_gauge`?

**Comment by Lincyaw** [comment]
> @Lincyaw which type do you have in `SELECT toTypeName(ResourceAttributes) FROM default.otel_metrics_gauge`?

The type is Map(LowCardinality(String), String). Currently, I use `toJSONString ` to transform the Map to json, does this is best practice?

**Comment by Slach** [comment]
no it should works with Map
let me check
actually i dind't find opel_metrics_gauge definition inside code
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/exporter/clickhouseexporter/

**Comment by Lincyaw** [comment]
> no it should works with Map let me check actually i dind't find opel_metrics_gauge definition inside code https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/exporter/clickhouseexporter/

It is here, `https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/internal/gauge_metrics.go`

**Comment by Slach** [comment]
@Lincyaw are you sure do you use 3.2.x plugin version? 
I don't see syntax highlight on shared screenshots

I tried to reproduce with `Map(LowCardinality(String),String)`, and everything works good


Let's try to rewrite the query a little bit to ensure:
`SELECT $timeSeries AS t, Value, MetricName, ResourceAttributes ...`
