### ISSUE TITLE
Additional time range for alerts doesn't work

### ISSUE THREAD

**Issue by fr05t1k** [Altinity/clickhouse-grafana#237]
It seems like an alert window doesn't work.

I specified that I'd like to check 3h window with 1h shift.
![image](https://user-images.githubusercontent.com/2131624/87313906-3a43aa00-c52b-11ea-9a39-6ded54b2efca.png)

This window is greater than 20%
![image](https://user-images.githubusercontent.com/2131624/87314315-b63df200-c52b-11ea-82b3-c5aad3096fdf.png)

But the alert checks the whole period of the graph.
![image](https://user-images.githubusercontent.com/2131624/87313841-25ffad00-c52b-11ea-9aa8-1b020be1e944.png)

**Comment by fr05t1k** [comment]
Index: datasource.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- datasource.go	(revision 35879b0fd7876201910adacc32de53d46cc90a18)
+++ datasource.go	(date 1594650002971)
@@ -63,7 +63,7 @@
 		return nil, fmt.Errorf("invalid status code. status: %v", response.Status)
 	}
 
-	return parseResponse(body, refId)
+	return parseResponse(body, refId, req.GetTimeRange())
 }
 
 func createRequest(req *datasource.DatasourceRequest, query string) (*http.Request, error) {
@@ -143,7 +143,7 @@
 	return request, nil
 }
 
-func parseResponse(body []byte, refId string) (*datasource.DatasourceResponse, error) {
+func parseResponse(body []byte, refId string, timeRange *datasource.TimeRange) (*datasource.DatasourceResponse, error) {
 	parsedBody := ClickHouseResponse{}
 	err := json.Unmarshal(body, &parsedBody)
 	if err != nil {
@@ -165,6 +165,10 @@
 					return nil, fmt.Errorf("unable to parse timestamp with alias t: %w", err)
 				}
 
+				if timeRange != nil && (timeRange.FromEpochMs > timestamp || timeRange.ToEpochMs < timestamp) {
+					continue
+				}
+
 				point, err := strconv.ParseFloat(v, 64)
 				if err != nil {
 					return nil, fmt.Errorf("unable to parse value for '%s': %w", k, err)

**Comment by fr05t1k** [comment]
Probably this patch could help
```
Index: datasource.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- datasource.go	(revision 35879b0fd7876201910adacc32de53d46cc90a18)
+++ datasource.go	(date 1594650002971)
@@ -63,7 +63,7 @@
 		return nil, fmt.Errorf("invalid status code. status: %v", response.Status)
 	}
 
-	return parseResponse(body, refId)
+	return parseResponse(body, refId, req.GetTimeRange())
 }
 
 func createRequest(req *datasource.DatasourceRequest, query string) (*http.Request, error) {
@@ -143,7 +143,7 @@
 	return request, nil
 }
 
-func parseResponse(body []byte, refId string) (*datasource.DatasourceResponse, error) {
+func parseResponse(body []byte, refId string, timeRange *datasource.TimeRange) (*datasource.DatasourceResponse, error) {
 	parsedBody := ClickHouseResponse{}
 	err := json.Unmarshal(body, &parsedBody)
 	if err != nil {
@@ -165,6 +165,10 @@
 					return nil, fmt.Errorf("unable to parse timestamp with alias t: %w", err)
 				}
 
+				if timeRange != nil && (timeRange.FromEpochMs > timestamp || timeRange.ToEpochMs < timestamp) {
+					continue
+				}
+
 				point, err := strconv.ParseFloat(v, 64)
 				if err != nil {
 					return nil, fmt.Errorf("unable to parse value for '%s': %w", k, err)
```

**Comment by Slach** [comment]
@fr05t1k thanks for reporting and provide the solution

I applied your patch, it works perfectly ;)

**Comment by Slach** [comment]
@fr05t1k now 2.5.0 release shall calculate time ranges for alerts properly
