### ISSUE TITLE
Backend Deprecation Warning

### ISSUE THREAD

**Issue by bmanth60** [Altinity/clickhouse-grafana#242]
The backend plugin has the following warning:
> Plugin uses a deprecated version of Grafana's backend plugin system which will be removed in a future release. Consider upgrading to a newer plugin version or reach out to the plugin repository/developer and request an upgrade." logger=plugins.backend pluginId=vertamedia-clickhouse-datasource

It needs to be updated with: https://github.com/grafana/grafana-plugin-sdk-go but this is still alpha

**Comment by Slach** [comment]
@bmanth60 could you help us switch to the new SDK?
new SDK not still alpha, but still in a development state, but protocol and API is stable

**Comment by bmanth60** [comment]
@Slach it may take a me a little while here but yeah, I am testing it out right now. I will update here on my status.

**Comment by Slach** [comment]
@bmanth60 sounds great ;) feel free to make PR

**Comment by Slach** [comment]
Hello @bmanth60, do you have any news about the switching process to the new golang SDK?

**Comment by bmanth60** [comment]
I got some of the frames mapped, but I don't think it is completely correct. Still doing more testing on this. I also need to rebase with master. It is getting there.

**Comment by Slach** [comment]
maybe we can write some unit tests for golang code?

**Comment by bmanth60** [comment]
stale

**Comment by Slach** [comment]
thanks for closing, unit tests written
