### ISSUE TITLE
Support for Logs in Grafana

### ISSUE THREAD

**Issue by pixelsquared** [Altinity/clickhouse-grafana#331]
Support for the "Logs" feature.

https://grafana.com/docs/grafana/latest/explore/logs-integration/
https://grafana.com/docs/grafana/latest/developers/plugins/build-a-logs-data-source-plugin/

Reason:

I am using ClickHouse as a log storage system and would like to be able to use the logs feature. I have a table with about over 300 columns for normalizing the logs fields, a column for the original log message, and a column for the log timestamp. For each row many of the normalization columns are NULL because many of the logs do not use all the fields so I was thinking that the Logs feature would work well for this.

Suggestion:

The idea is I could map the columns to the fields required for the Logs feature like timestamp and the log message and than for the other fields in each row add any non-null values as additional fields in the result.

Would this be something you would consider? I am willing to help just need some help on where I need to modify because I am not familiar with Grafana data source plugins.

**Comment by Slach** [comment]
@pixelsquared thanks a lot for suggestions
if you wish to make pull request
please read https://github.com/Vertamedia/clickhouse-grafana/blob/master/CONTRIBUTING.md will good point of start

also look to https://github.com/Vertamedia/clickhouse-grafana/tree/master/src 

but after reading your links, it's not clear for me
which "query" will send from Grafana Logs UI? It will SQL query? Or something like LogsQL for Loki ?

**Comment by pixelsquared** [comment]
@Slach I was thinking the query would just be a "WHERE" clause. Does that make sense or do you think there is a better way?

**Comment by pixelsquared** [comment]
@Slach From what I have read in the Grafana docs it looks like we would need an option in the data source configuration to choose if it will use the logs explore page or the metrics one.

https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-explore-queries/#selecting-preferred-visualisation

**Comment by Slach** [comment]
@pixelsquared looks like a good point to start, could try to make pull request?
for properly building you need to create `.release_env`
```
export GITHUB_LOGIN="XXX"
export GITHUB_EMAIL="XXX"
export GITHUB_TOKEN="XXXX"
# you can try to submit your own API_KEY via https://grafana.com/orgs/YOUR_ACCOUNT_LOGIN/api-keys
export GRAFANA_API_KEY=XXXX
```
