### ISSUE TITLE
Support for subsecond intervals

### ISSUE THREAD

**Issue by oplehto** [Altinity/clickhouse-grafana#344]
It seems that it's not possible to have sub-second precision on graphs. This looks like it's due to a hard limit of 1 second for the `$timeSeries` macro:
https://github.com/Vertamedia/clickhouse-grafana/blob/2f2d2e164848ac0c54d745ab8d7ec301dc2c948a/src/sql_query.ts#L530-L532

A workaround is to use `$__interval_ms` instead of `$interval`. For example:
```
(intDiv(toFloat64("_time") * 1000, $__interval_ms) * $__interval_ms) AS t,
```

Adding  support for `$interval` to be < 1 would be handy but it might have some side-effects I didn't check for. Thus it may make more sense to change the `$timeSeries` to use `$__interval_ms` here: 

https://github.com/Vertamedia/clickhouse-grafana/blob/2f2d2e164848ac0c54d745ab8d7ec301dc2c948a/src/sql_query.ts#L467

**Comment by Slach** [comment]
I think we can apply $__interval_ms

**Comment by Slach** [comment]
@oplehto you can't select subsecond interval from grafana itself in range queries widget, so i not sure how it can be applicable
![image](https://user-images.githubusercontent.com/105560/143905505-8ff1cd5d-64ad-4e17-a26f-6cb6f227997c.png)


currently we implements `$timeFilter64ByColumn` which will release on 2.4.0

**Comment by Slach** [comment]
@oplehto could you provide more use-cases for your proposal?
