### ISSUE TITLE
[Feature] Support for "Node Graph" panel

### ISSUE THREAD

**Issue by hyberdk** [Altinity/clickhouse-grafana#352]
Hi all, 

I was wondering if there are support for the new Node Graph panel plugin in the clickhouse datasource?

This is the one that I am talking about:
https://grafana.com/docs/grafana/latest/panels/visualizations/node-graph/

As far as I can see, there needs to be some special data frames returned. If there already are support, then do anyone have a working installation running or can you point to some better documentation than what is on the grafana.com docs?

Thanks a lot.

Esben

**Comment by Slach** [comment]
@hyberdk thanks a lot for your reporting
I will try add this functionality to next release

**Comment by hyberdk** [comment]
@Slach that would be awesome, let me know if you need someone to test or something like that.. 

Unfortunately the languages you use in this project is not really my flavor, so help coding is not realistic ;-)

**Comment by lmangani** [comment]
@Slach are you targetting 8,x or 7.x? Not sure if this is still the case right now, but there were some hardcoded limitations in 7.x preventing normal [datasources from working](https://github.com/grafana/grafana/issues/30630) due to the `preferredVisualisationType`

**Comment by lmangani** [comment]
Surprisingly, this actually works without any modifications! 

Node Graph can be fed using two different table formatted (A,B) queries with the following mandatory fields in each:

- `nodes`
  - id *(distinct, unique)*
  - title
- `edges`
  - id *(ie: concat(source,target))*
  - source
  - target

*Note all the objects in source + target edges must exist as node ids for the panel to work!*

The full list of optional parameters is available [here](https://grafana.com/docs/grafana/latest/panels/visualizations/node-graph/#data-api)

![image](https://user-images.githubusercontent.com/1423657/127058543-2ddaa585-a907-4d3b-8f10-4ec54fb48443.png)

**Comment by iamshreeram** [comment]
Hi @lmangani, I hope you're doing well. 

Does this setup without requiring any plugins?
We're currently publishing OpenTelemetry metrics to ClickHouse, and we're trying to view the data in node graph. However, it appears that the node graph isn't displaying any information, even though the query itself is returning the expected results. 

I've attached a screenshot for your reference. I would really appreciate any assistance you can provide. Thank you!

<img width="850" alt="image" src="https://github.com/user-attachments/assets/b40959a3-2bc2-45a1-8033-9ebb8b028cea">

**Comment by lmangani** [comment]
@iamshreeram at the time of writing it did but Grafana is ever changing so they probably broke this capability. Which version are you using? If you want something to do this nicely out of the box with ClickHouse check our project [qryn](https://github.com/metrico/qryn) which does this (and much more) natively and supports the full tempo API 😉
