### ISSUE TITLE
Difficult to use if only Date column is present (and there is no DateTime column)

### ISSUE THREAD

**Issue by alexey-milovidov** [Altinity/clickhouse-grafana#367]
Workaround: add `WITH toDateTime($dateCol) AS undefined` to the query.
But that's exceptionally ugly.

**Comment by Slach** [comment]
Thanks a lot for reporting, will fix on next version

**Comment by Slach** [comment]
@alexey-milovidov could you provide more context?
What was hard? `UI` and graphs part or alerts part?

**Comment by Slach** [comment]
@alexey-milovidov didn't provide any additional context

**Comment by alexey-milovidov** [comment]
We no longer use the Grafana plugin from Vertamedia, because the official ClickHouse plugin for Grafana exists.
