### ISSUE TITLE
[Enhancement]Support UInt64 unix timestamp with millisecond as datetime

### ISSUE THREAD

**Issue by ever4Kenny** [Altinity/clickhouse-grafana#371]
![image](https://user-images.githubusercontent.com/13478259/136651067-90cf01d0-fd2c-4b71-88f4-c543205afe20.png)
Currently we only support Datetime\DateTime\Timestmap(Unix timestamp with second) as datetime. However in some case, there are data using unix timestamp with millisecond as datetime(such as logs etc.). Should we support this?

**Comment by ever4Kenny** [comment]
I've edited the frontend part(without backend change) and tested it with grafana 8.1.1. It looks good to me and the data could be correctly filtered and displayed . Could you please shed some light on which golang part should be looked into?

**Comment by Slach** [comment]
@ever4Kenny any news about this enhancement?

**Comment by mixayloff-dimaaylov** [comment]
Any updates on this? For me `$columns` with time column set to `column:TimeStamp`
returns incorrect query. `$timeFilterMs` also returns incorrect query. I forced to correct it
by multiplying the time column by 1000.

This can be done as in PR #46, which ads `TimeStampMs` column datatype for `UInt64` columns.

You can look at the port of this for the new version, but I'm not sure of the absolute correctness.
And I'm having problems with alerts like in #447 .
