### ISSUE TITLE
Unexpected behaviour with clickhouse datasource  (v2.3.1) and single stat panel 

### ISSUE THREAD

**Issue by toni-moreno** [Altinity/clickhouse-grafana#403]
Hello Guys. I'm trying to create a Grafana 7.5.5 Dashboard with single stat panel like in others dashboarsd we have already working fine, but with  unexpected behaviour  with clickhouse datasource. 

## Data visualization with flux/influxdb

With other datasources (flux/influxdb) we have created a singlestat that we can feed with a table like that  (from chronograf)
with 2 entries.
![image](https://user-images.githubusercontent.com/5883405/148555202-52ceb0a0-b1cc-4622-84af-859215aa52d4.png)

with this singlestat result
![image](https://user-images.githubusercontent.com/5883405/148555417-067cb257-cc81-45b5-bf16-a21df7918e22.png)

or this other with 1 entry
![image](https://user-images.githubusercontent.com/5883405/148555281-a7197907-2f3c-46aa-9ad1-5686223e608a.png)

And this result.

![image](https://user-images.githubusercontent.com/5883405/148555583-94616978-6d9f-4709-b9e9-d235ee9c2fa8.png)

## Data visualization with clickhouse

when result for the query is that ( assuming that we should add a fake time column) 
```
┌─t─┬─cat─┬─errors─┐
│ 1 │   3 │     24 │
│ 1 │   4 │     84 │
└───┴─────┴────────┘
```

visualization is ok

![image](https://user-images.githubusercontent.com/5883405/148556074-0b5d816f-1f05-499e-b69d-7edb3da2c112.png)

when result for the query is this other.

```
┌─t─┬─cat─┬─errors─┐
│ 1 │   4 │     84 │
└───┴─────┴────────┘
```
![image](https://user-images.githubusercontent.com/5883405/148556288-2d7cf44a-34a1-4bcf-aed0-d1cb0766fdc9.png)

the category column information /(tag in influxdb) disappeared.

There is any way to fix this behaviour difference with other datasources?

**Comment by Slach** [comment]
Could you try a different approach?
```
┌─t─┬─cat─┬─errors─┐
│ 1 │   Category 4 │     84 │
└───┴─────┴────────┘
```
I mean select `cat` field as string which not contain only numbers

**Comment by toni-moreno** [comment]
Hello @Slach  I've replaced my original .
```
SELECT
    1 AS t, /* fake timestamp value */
    cat,
    count(idx) as errors
FROM
(
....( another big subselect) 
)
WHERE 
GROUP BY t,cat
```
by 
```
SELECT
    1 AS t, /* fake timestamp value */
    concat('Category ',toString(cat)) as cat,
    count(idx) as errors
FROM
(
....( another big subselect) 
)
WHERE 
GROUP BY t,cat
```
now Grafana is getting strings en cat column

```
┌─t─┬─cat────────┬─errors─┐
│ 1 │ Category 3 │     24 │
│ 1 │ Category 4 │     84 │
└───┴────────────┴────────┘
```

![image](https://user-images.githubusercontent.com/5883405/148616441-a498a962-13cc-462d-a860-7ef0246fd3d2.png)


```
┌─t─┬─cat────────┬─errors─┐
│ 1 │ Category 3 │     24 │
└───┴────────────┴────────┘
```
And still not working when only one row.

![image](https://user-images.githubusercontent.com/5883405/148616579-cc8fddf8-7550-4a87-84b8-fa879b0653e5.png)

**Comment by Slach** [comment]
Could you try to replace your clickhouse query format from `time series` to `table`? (look drop-down menu on bottom)

or try to replace your query and apply $columns macro

```sql
$columns(
    concat('Category ',toString(cat)) as cat,
    count(idx) as errors
) FROM
(
....( another big subselect) 
)
GROUP BY t,cat
```

**Comment by toni-moreno** [comment]
Hello again @Slach . 
I've tested both solutions

# 1) With timeseries format
 ## Option A
I've tested 2 options, and neither of them are valid because main information "Category" has disappeared
```sql
SELECT
    1 AS t, /* fake timestamp value */
    concat('Category ',toString(cat)) as cat,
    count(idx) as errors
FROM
(
    ....( another big subselect) 
)
GROUP BY t,cat
```

this table 
```
┌─t─┬─cat────────┬─errors─┐
│ 1 │ Category 3 │     24 │
│ 1 │ Category 4 │     84 │
└───┴────────────┴────────┘
```
will become  in
![image](https://user-images.githubusercontent.com/5883405/148728350-152499fe-356d-4e45-a7d6-d19fd0bfea33.png)

## Option B ( without t) 
```sql
SELECT
    concat('Category ',toString(cat)) as cat,
    count(idx) as errors
FROM
(
    ....( another big subselect) 
)
GROUP BY cat
```

this table
```
┌─cat────────┬─errors─┐
│ Category 3 │     24 │
│ Category 4 │     84 │
└────────────┴────────┘
```
will become in 
![image](https://user-images.githubusercontent.com/5883405/148728611-4d19d4d4-8f1e-4ebc-aa63-36411b7202ba.png)

# 2.- with $columns macro

this query
```
$columns(
    concat('Category ',toString(cat)) as cat,
    count(idx) as errors
) FROM
(
....( another big subselect) 
)
GROUP BY t,cat
```
will transform to this other.
```
SELECT t, groupArray((cat, errors)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time), 2) * 2) * 1000 AS t, concat('Category ', toString(cat)) as cat, count(idx) as errors FROM
(
....( another big subselect) 
)
GROUP BY t,cat GROUP BY t, cat ORDER BY t, cat) GROUP BY t ORDER BY t
```
I'm not sure what is supposed to do this macro but it is failing with this error

```
Code: 62. DB::Exception: Syntax error: failed at position 685 ('GROUP') (line 20, col 16): GROUP BY t, cat ORDER BY t, cat) GROUP BY t ORDER BY t FORMAT JSON . Expected one of: token, Comma, Arrow, Dot, UUID, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT. (SYNTAX_ERROR) (version 21.12.3.32 (official build))
```

any other suggestion ?

**Comment by Slach** [comment]
Let's try remove `intDIv` and double group by 
something like that

```sql
SELECT t, groupArray((cat, errors)) AS groupArr FROM ( 

  SELECT 
     1 AS t, 
     concat('Category ', toString(cat)) as cat, 
     count(idx) as errors 
  FROM (

....( another big subselect) 

  )
  GROUP BY t, cat ORDER BY t, cat
) 
GROUP BY t 

```

Did you try to replace your clickhouse query format from time series to table? (look drop-down menu on bottom)

**Comment by toni-moreno** [comment]
Yes @Slach  while this  query.
```sql
 SELECT 
     1 AS t, 
     concat('Category ', toString(cat)) as cat, 
     count(idx) as errors 
  FROM (

....( another big subselect) 

  )
  GROUP BY t, cat ORDER BY t, cat
```
I'm getting this table.
```
┌─t─┬─cat────────┬─error─┐
│ 1 │ Category 3 │    24 │
│ 1 │ Category 4 │    84 │
└───┴────────────┴───────┘
```
with this result ( Formatted as Table) 
![image](https://user-images.githubusercontent.com/5883405/148789358-276b5741-1ae9-451e-8a77-8a06be4fc918.png)

When adding the groupArray  extension
```sql
SELECT t, groupArray((cat, error)) AS groupArr FROM ( 

  SELECT 
     1 AS t, 
     concat('Category ', toString(cat)) as cat, 
     count(idx) as error
FROM
(
....( another big subselect) 

  )
  GROUP BY t, cat ORDER BY t, cat
) 
GROUP BY t 
```
I got this table

```
┌─t─┬─groupArr──────────────────────────────┐
│ 1 │ [('Category 3',24),('Category 4',84)] │
└───┴───────────────────────────────────────┘
```
And This as single stat.

**Configuring Numeric Fields** 

![image](https://user-images.githubusercontent.com/5883405/148790428-b0d10efb-154d-4477-8b66-f46d8957654f.png)

**Configuring All fields.**

![image](https://user-images.githubusercontent.com/5883405/148790565-e7a84acd-8a7a-4b3f-8a3b-052cf771ca64.png)

**And configuring only GroupArr field**

![image](https://user-images.githubusercontent.com/5883405/148790781-e4efe7f5-19a2-4af2-b002-e8a2711c6c59.png)


### Expected 

![image](https://user-images.githubusercontent.com/5883405/148791701-40e9e55b-8539-441a-ac85-386b7f49cb54.png)

All previous queries and configurations never got expected result.
 
Maybe we won't be able to configure single stats as expected if no way to get data as dataframes , see related issue (https://github.com/Vertamedia/clickhouse-grafana/issues/404)

**Comment by Slach** [comment]
### I ask third time!!! Did you try to replace your clickhouse query format from `time series` to `table`? (look drop-down menu on bottom)?

![image](https://user-images.githubusercontent.com/105560/148797235-7e0679f4-f94b-436f-a4bd-7614b0e999b2.png)

**Comment by Slach** [comment]
ok ;) clear, thanks a lot for reporting, i will try to figure wrong behavior ASAP

**Comment by toni-moreno** [comment]
Thank you very much for your time @Slach . 

As I said in my first entry in this issue, we have currently working with single stats panel, and I think all this behaviour could be fixed by only getting data in grafana dataframe format ( needed for Grafana 7.0+ ). Thank you very much again for your work.

**Comment by Slach** [comment]
@lunaticusgreen need to figure out how works result set with category with single stat visualization in Grafana 10

**Comment by Slach** [comment]
@toni-moreno sorry for late reply
is issue still relevant for you?

**Comment by Slach** [comment]
@lunaticusgreen let's add `./docker/grafana/dashboards/singlestat.json` which will reproduce (or not) behavior in https://github.com/Altinity/clickhouse-grafana/issues/403#issuecomment-1008998631
