### ISSUE TITLE
Legacy binary on dist, docker-compose backend builder and zip release

### ISSUE THREAD

**Issue by sbengo** [Altinity/clickhouse-grafana#419]
It seems that there is some legacy binary referenced on several places:

- The binary on dist folder has a wrong name  https://github.com/Altinity/clickhouse-grafana/blob/master/dist/atinity-clickhouse-plugin_linux_amd64
```
atinity-clickhouse-plugin_linux_amd64
```

- And it is referenced as output binary when building from source using the master docker-compose.yml, which is not loaded by Grafana after a restart due to wrong name

https://github.com/Altinity/clickhouse-grafana/blob/53649cbb96684d2517a75281be4e11d6282a356c/docker-compose.yaml#L97

- The current release zip 2.4.4 also contains the legacy binary:

```
755 (-rwxr-xr-x) vertamedia-clickhouse-plugin_linux_arm64 
755 (-rwxr-xr-x) altinity-clickhouse-plugin_linux_amd64 
755 (-rwxr-xr-x) altinity-clickhouse-plugin_linux_arm64 
755 (-rwxr-xr-x) vertamedia-clickhouse-plugin_linux_amd64 
--> 644 (-rw-r--r--) atinity-clickhouse-plugin_linux_amd64 
```

**Comment by Slach** [comment]
oops ;( it's strange, `altinity-clickhouse-plugin_linux_amd64` is the right name, but really strange miss execute attribute
will check tomorrow

look like we need to make a new release

**Comment by sbengo** [comment]
@Slach , it doesn't break anything, as the right `altinity-clickhouse-plugin_linux_amd64` exists, it is only there seems to be an old binary on there with wrong name.

Only found problems when tried to compile it using docker-compose as the output had the wrong name
