### ISSUE TITLE
HTTP Error Bad Gateway?

### ISSUE THREAD

**Issue by vincentff7** [Altinity/clickhouse-grafana#424]
when i use postman, it is ok.
however, in grafana clickhouse datasource, it fails :HTTP Error Bad Gateway?
log shows:
t=2022-05-16T16:19:33+0800 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/ remote_addr=[::1] referer=http://localhost:3000/datasources/edit/1/ error="http: proxy error: dial tcp 127.0.0.1:8132: connectex: No connection could be made because the target machine actively refused it."
t=2022-05-16T16:19:33+0800 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/ status=502 remote_addr=[::1] time_ms=2046 size=0 referer=http://localhost:3000/datasources/edit/1/

**Comment by Slach** [comment]
which clickhouse host do you use in data source properties?

**Comment by Slach** [comment]
`remote_addr=[::1]`

are you sure your clickhouse-server setup in the same machine as grafana?
and listen `::1` ipv6 address?

could you replace host in datasource properties to 127.0.0.1 ?

**Comment by vincentff7** [comment]
> `remote_addr=[::1]`
> 
> are you sure your clickhouse-server setup in the same machine as grafana? and listen `::1` ipv6 address?
> 
> could you replace host in datasource properties to 127.0.0.1 ?

i installed grafana 7.3.2 with two versions: windows installer version and docker version. 
with the plugin 2.4.4, and config:
127.0.0.1:8123
server
basic auth  root/root
CORS flags on

**one success and one fail.**

**in windows version**, it sucesses: Data source is working


however **in docker version**, it still shows: HTTP Error Bad Gateway. with log
t=2022-05-16T09:16:49+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/ remote_addr=172.17.0.1 referer=http://localhost:3001/datasources/edit/1/ error="http: proxy error: dial tcp 127.0.0.1:8123: connect: connection refused"

t=2022-05-16T09:16:49+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/ status=502 remote_addr=172.17.0.1 time_ms=20 size=0 referer=http://localhost:3001/datasources/edit/1/

**Comment by Slach** [comment]
When you run `grafana` in docker, you should use IP address of `clickhouse-server` docker container instead of 127.0.0.1

Could you share  `docker ps` command result?

or try to use docker-compose, 
look 
https://github.com/Altinity/clickhouse-grafana/blob/master/docker-compose.yaml
for examples
and you should use "clickhouse" as host

**Comment by vincentff7** [comment]
> docker ps

thanks! it works! 
i used my PC IP address instead of 127.0.0.1 in grafana datasource in docker. it works!
