### ISSUE TITLE
`$timeFilter` for DateTime64 with precision != 3 works much slower

### ISSUE THREAD

**Issue by loyd** [Altinity/clickhouse-grafana#425]
The current implementation forces casting to `DateTime64(.., 3)`:
https://github.com/Altinity/clickhouse-grafana/blob/e7d2d2062632cc49c734f25179efe3e680382c29/src/sql_query.ts#L530

It works much slower for other precisions. For instance, we have `DateTime64(.., 9)`: 
```
SELECT (intDiv(toFloat64(platform_time) * 1000, (5 * 1000)) * (5 * 1000)) AS t, value FROM ...
WHERE toDateTime64(platform_time, 3) >= toDateTime64(1652710328, 3)
  AND toDateTime64(platform_time, 3) <= toDateTime64(1652713930, 3)
ORDER BY platform_time
```
`Processed 1.36 million rows`

vs

```
SELECT intDiv(toFloat64(platform_time) * 1000, 5 * 1000) * (5 * 1000) AS t, value FROM ...
WHERE (platform_time >= toDateTime(1652710328))
  AND (platform_time <= toDateTime(1652713930))
ORDER BY platform_time
```
`Processed 24.58 thousand rows`

Related to https://github.com/Altinity/clickhouse-grafana/issues/292

**Comment by Slach** [comment]
which plugin version do you use?

2.4.0 remove dateTime64 type casting
look https://github.com/Altinity/clickhouse-grafana/pull/370/files
and https://github.com/Altinity/clickhouse-grafana/issues/360

please upgrade plugin and feel free to reopen issue if performance still bad

**Comment by Slach** [comment]
Issue was related with ClickHouse itself which have bad DateTime64 compare https://github.com/ClickHouse/ClickHouse/issues/16655
