### ISSUE TITLE
Clickhouse plugin causes the graph panel plugin to drop

### ISSUE THREAD

**Issue by Nikolina697** [Altinity/clickhouse-grafana#431]
I opened an issue #421, which was supposed to be fixed in version 2.5.0 of the datasource plugin.
I tested in grafana v8.1.8 and it seems that after applying the adhoc filter graph panel it still crash.
I'm using the same query which I put in the first issue. Error that I'm getting in the top left corner of graph panel:
 
![Screenshot from 2022-06-20 17-55-20](https://user-images.githubusercontent.com/61902055/174640837-5e4a6614-e348-457f-af14-bfc87315c619.png)

I really appreciate your effort!

**Comment by Slach** [comment]
Could you share  source SQL query with macros
and 
"generated SQL"
after adhoc filter changed?

**Comment by Nikolina697** [comment]
Here are SQL query with macros **after adhoc filter** has been applied:
```
WITH topx as(select DISTINCT(case when $split :: text = '' then 'other'::text else $split::text end)::text as filter, count() as cnt from $table where $timeFilter and $adhoc group by $split order by cnt desc limit 10)

SELECT
    $timeSeries as t,
    case when $split :: text in (select filter from topx) then $split::text else 'other' end :: text as spl,
    count()
FROM $table data
WHERE
    $timeFilter
    and $adhoc
GROUP BY  spl, t
ORDER BY  spl, t 
```
and Generated SQL **after adhoc filter** has been applied:
```
WITH topx as(select DISTINCT(case when user : : text = '' then 'other' : : text else user : : text end) : : text as filter, count() as cnt from database.table where referencetime >= toDateTime(1655706655) AND referencetime <= toDateTime(1655793055) and (email = 'user@email.com') group by user order by cnt desc limit 10)
SELECT
    (intDiv(toUInt32(referencetime), 1800) * 1800) * 1000 as t,
    case when user : : text in (
    SELECT filter

    FROM topx
) then user : : text else 'other' end : : text as spl,
    count()
FROM database.table data

WHERE
    referencetime >= toDateTime(1655706655) AND referencetime <= toDateTime(1655793055)
    and (email = 'user@email.com')
GROUP BY
    spl,
    t
ORDER BY
    spl,
    t
```
According to the generated SQL I see that after the adhoc filter is applied the SQL query becomes malformed and simply the clickhouse database does not recognize it, that's my view.

**Comment by Slach** [comment]
look to https://github.com/Altinity/clickhouse-grafana/blob/master/docker/grafana/dashboards/adhoc_variable_text_select_in_issue_421.json#L123

try to use `${split::text}`

**Comment by Nikolina697** [comment]
You are right, when I change the query in accordance with the changes from the link it works, thank you.
