### ISSUE TITLE
Cannot correctly escape table name containing "-" symbol

### ISSUE THREAD

**Issue by chenlujjj** [Altinity/clickhouse-grafana#440]
Suppose database name is "test", table name is "a.b.c-d", then the escaped result is "test.a.b.c-d", it will lead to syntax error in sql.

Expected result is "test.`a.b.c-d`", it will work.

Maybe some change shoule be made to `func (q *EvalQuery) escapeIdentifier(identifier string) string` ？

**Comment by Slach** [comment]
Sorry for late response,

could you share your ogirinal query with $table macro?
and query which you see in "Generated SQL"?

**Comment by chenlujjj** [comment]
original query:
```
SELECT
    $timeSeries as t,
    count()
FROM $table

WHERE $timeFilter

GROUP BY t

ORDER BY t

```

generated sql:
```
SELECT
    (intDiv(toFloat64(timestamp) * 1000, (5 * 1000)) * (5 * 1000)) as t,
    count()
FROM test.a.b.c-d

WHERE toDateTime64(timestamp, 3) >= toDateTime64(1661337946, 3)

GROUP BY t

ORDER BY t
```

**Comment by Slach** [comment]
lets wait when grafana team will review https://github.com/Altinity/clickhouse-grafana/releases/tag/v2.5.1

**Comment by chenlujjj** [comment]
Cool!

**Comment by Slach** [comment]
same changes applied to golang part to
look to https://github.com/Altinity/clickhouse-grafana/commit/8dfba84ac85b58c9667471e25d39cf87a6593892 for details

**Comment by visago** [comment]
> lets wait when grafana team will review https://github.com/Altinity/clickhouse-grafana/releases/tag/v2.5.1

We still need to wait for Grafana team to update something before 2.5.1 will work ?

**Comment by Slach** [comment]
@visago 2.5.1 released on grafana.com, just install new plugin version

**Comment by visago** [comment]
Ah ! okay, yeah just did a grafana-cli plugins install vertamedia-clickhouse-datasource 2.5.1 !

**Comment by visago** [comment]
I just tested 2.5.1 and getting the same issue. I noticed escapeTableIdentifier function was created in src/sql_query.ts, but its not called like in the go code ? 

https://github.com/Altinity/clickhouse-grafana/blob/master/src/sql_query.ts#L122-L125

**Comment by Slach** [comment]
@visago 2.5.2 released, please test

**Comment by visago** [comment]
@Slach tested and verified working ! Thanks so much for the quick response !
