### ISSUE TITLE
How to build this plugin locally and install into grafana server?

### ISSUE THREAD

**Issue by chenlujjj** [Altinity/clickhouse-grafana#441]
I modified a few lines of code and want to see whether it works. But I don't know how to build it locally. 
It would be better if the solution does not depend on docker.

**Comment by Slach** [comment]
look to https://github.com/Altinity/clickhouse-grafana/blob/master/CONTRIBUTING.md for details

**Comment by Slach** [comment]
You are welcome to make pull request with your contributions

**Comment by chenlujjj** [comment]
Thanks!  However, the contributing guide depends heavily on docker-compose, which is inconvenient to me for some reason. Actually I figured out the build and package process by investigating on the github workflow file. Anyway, it works.
