### ISSUE TITLE
Plugin log doesn't appear in grafana server logs

### ISSUE THREAD

**Issue by chenlujjj** [Altinity/clickhouse-grafana#442]
I want to do some debug on this plugin and I add a few logs in backend code, for example:
in `pkg/client.go`
```go
func (client *ClickHouseClient) Query(ctx context.Context, query string) (*Response, error) {
	backend.Logger.Info("ClickHouseClient Query: %s", query)
         ...
}
```
I packaged and installed the new plugin into grafana, then restarted grafana server, refreshed panels. But the log didn't appear at all.

Have I missed something here ?

**Comment by chenlujjj** [comment]
Grafana version: 9.0.6
Plugin version: 2.5.0

**Comment by Slach** [comment]
you can defined GF_LOG_LEVEL: debug environment
look details here https://github.com/Altinity/clickhouse-grafana/blob/master/docker-compose.yaml#L54
or configure log level via `grafana.ini` 
look https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#log for details

queries which used in Query and EvalQuery should display in grafana server logs

**Comment by chenlujjj** [comment]
> GF_LOG_LEVEL: debug
Probably it's not a issue of log level, the default log level if INFO and I didn't change it.

I can see the  `"Starting ClickHouse datasource backend..."` log in `main.go`:

![image](https://user-images.githubusercontent.com/17081528/185857776-73e5c25b-09c6-434a-bf6d-fe72fe4cb25f.png)

But other logs I added in Query, EvalQuery and CheckHealth didn't appear.

**Comment by Slach** [comment]
it's trange
cause according to
https://github.com/Altinity/clickhouse-grafana/blob/master/pkg/datasource.go#L62

every query shall show in debug log

**Comment by chenlujjj** [comment]
> it's trange cause according to https://github.com/Altinity/clickhouse-grafana/blob/master/pkg/datasource.go#L62
> 
> every query shall show in debug log


`backend.Logger.Debug(fmt.Sprintf("queryResponse: %s returns %v frames", sql, len(frames)))`
I set log level to debug, but still could not find the above log in log files. 

![image](https://user-images.githubusercontent.com/17081528/185893546-77b49886-fc0b-4043-9b02-719c1d53f8dc.png)

**Comment by Slach** [comment]
How exactly do you change your log level? did you change grafana.ini ?

Did you restart your `grafana-server` after change log level?

if your log level is debug you, shall see something like
```
logger=plugin.vertamedia-clickhouse-datasource t=2022-08-23T05:33:01.0886289Z level=debug msg="queryResponse: SELECT\n    (intDiv(toUInt32(EventTime), 2) * 2) * 1000 as t,\n    Name,\n    sum(Value) v\nFROM default.test_alerts\n\nWHERE EventTime >= toDateTime(1661225581) AND EventTime <= toDateTime(1661225881) AND Name in ('test1','test2')\n\nGROUP BY t, Name\n\nORDER BY t, Name FORMAT JSON /* alerts query */; returns 0 frames"

```
