### ISSUE TITLE
request handler error: plugin unavailable

### ISSUE THREAD

**Issue by sdarshil** [Altinity/clickhouse-grafana#447]
Hello altinity team ,
i am trying to use the altinity dashboard for clickhouse operator and it is working fine .
But when i try to setup alert for this dashboard , i am getting this error :
request handler error: plugin unavailable
![image](https://user-images.githubusercontent.com/31997374/190127381-d6abedc5-75b7-48d4-929c-0bf876a7c4ce.png)

I am using the latest version available of the altinity clickhouse plugin !

**Comment by Slach** [comment]
which grafana version do you use?

how you setup Altinity grafana plugin?

could  you share
```
ls -la /var/lib/grafana/plugins/vertamedia-clickhouse-datasource/
```

**Comment by sdarshil** [comment]
bash-5.1$ ls -la /var/lib/grafana/plugins/vertamedia-clickhouse-datasource/
total 108136
drwxrwsr-x    4 grafana  472           4096 Sep  8 08:35 .
drwxrwsr-x    4 grafana  472           4096 Sep  9 08:31 ..
-rw-rw-r--    1 grafana  472           1106 Sep  8 08:35 LICENSE
-rw-rw-r--    1 grafana  472           2541 Sep  8 08:35 MANIFEST.txt
-rw-rw-r--    1 grafana  472          26715 Sep  8 08:35 README.md
-rwxrwxr-x    1 grafana  472       21166624 Sep  8 08:35 altinity-clickhouse-plugin_darwin_amd64
-rwxrwxr-x    1 grafana  472       20837602 Sep  8 08:35 altinity-clickhouse-plugin_darwin_arm64
-rwxrwxr-x    1 grafana  472       21504577 Sep  8 08:35 altinity-clickhouse-plugin_linux_amd64
-rwxrwxr-x    1 grafana  472       20676890 Sep  8 08:35 altinity-clickhouse-plugin_linux_arm64
-rwxrwxr-x    1 grafana  472       21835264 Sep  8 08:35 altinity-clickhouse-plugin_windows_amd64.exe
drwxrwsr-x    2 grafana  472           4096 Sep  8 08:35 img
-rw-rw-r--    1 grafana  472        1227271 Sep  8 08:35 module.js
-rw-rw-r--    1 grafana  472        3411046 Sep  8 08:35 module.js.map
drwxrwsr-x    2 grafana  472           4096 Sep  8 08:35 partials
-rw-rw-r--    1 grafana  472           1192 Sep  8 08:35 plugin.json


------

Grafana v8.5.4

--------

downloaded via grafana-cli

**Comment by sdarshil** [comment]
The plugin is working but the alert is not setting up

**Comment by Slach** [comment]
Could you configure debug log level in /etc/grafana/grafana.ini, restart grafana-server 
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#log
and search `vertamedia` in grafana-server logs? (for example 
journalctl -xe --no-pager -u grafana-server)

if you use docker or docker-compose just define GF_LOG_LEVEL=debug environment
like here https://github.com/Altinity/clickhouse-grafana/blob/master/docker-compose.yaml#L54

**Comment by Slach** [comment]
> The plugin is working but the alert is not setting up

plugin have two parts, backend golang part which evalute alerts and frontend part which works in browser and use grafana server as proxy to connect to clickhouse

**Comment by sdarshil** [comment]
we have configured the grafana on kubernetes , i have configured log level debug and here is the logs :

```
logger=alerting.resultHandler t=2022-09-15T06:23:06.69+0000 lvl=info msg="New state change" ruleId=9369 newState=ok prevstate=unknown
logger=alerting.engine t=2022-09-15T06:23:06.69+0000 lvl=dbug msg="Job Execution completed" timeMs=2.95125 alertId=9356 name="Chi Down ALert" firing=false attemptID=1
logger=alerting.resultHandler t=2022-09-15T06:23:06.7+0000 lvl=info msg="New state change" ruleId=9368 newState=ok prevstate=unknown
logger=alerting.engine t=2022-09-15T06:23:06.73+0000 lvl=dbug msg="Job Execution attempt triggered retry" timeMs=44.712462 alertId=9079 name="CPU Wait Time alert" firing=true attemptID=1
logger=alerting.engine t=2022-09-15T06:23:06.73+0000 lvl=dbug msg="Job Execution attempt triggered retry" timeMs=0.516526 alertId=9079 name="CPU Wait Time alert" firing=true attemptID=2
logger=alerting.evalContext t=2022-09-15T06:23:06.73+0000 lvl=eror msg="Alert Rule Result Error" ruleId=9079 name="CPU Wait Time alert" error="request handler error: plugin unavailable" changingstateto=alerting
logger=alerting.engine t=2022-09-15T06:23:06.73+0000 lvl=dbug msg="Job Execution completed" timeMs=0.40602 alertId=9079 name="CPU Wait Time alert" firing=true attemptID=3
```


```
logger=plugin.loader t=2022-09-15T06:22:12.05+0000 lvl=dbug msg="Loading plugin" path=/var/lib/grafana/plugins/vertamedia-clickhouse-datasource/plugin.json
logger=plugin.loader t=2022-09-15T06:22:12.39+0000 lvl=dbug msg="Plugin signature valid" id=grafana-clickhouse-datasource
logger=plugin.loader t=2022-09-15T06:22:15.47+0000 lvl=dbug msg="Plugin signature valid" id=vertamedia-clickhouse-datasource
logger=plugin.signature.validator t=2022-09-15T06:22:15.47+0000 lvl=dbug msg="Plugin has valid signature" id=grafana-clickhouse-datasource
logger=plugin.signature.validator t=2022-09-15T06:22:15.47+0000 lvl=dbug msg="Plugin has valid signature" id=vertamedia-clickhouse-datasource
logger=plugin.manager t=2022-09-15T06:22:15.47+0000 lvl=info msg="Plugin registered" pluginId=grafana-clickhouse-datasource
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:22:15.47+0000 lvl=dbug msg="starting plugin" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64 args="unsupported value type"
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:22:15.48+0000 lvl=dbug msg="plugin started" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64 pid=18
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:22:15.48+0000 lvl=dbug msg="waiting for RPC address" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:22:15.5+0000 lvl=info msg=Profiler enabled=false
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:22:15.5+0000 lvl=dbug msg="Serving plugin" plugins="unsupported value type"
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:22:15.53+0000 lvl=dbug msg="plugin address" address=/tmp/plugin262358571 network=unix
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:22:15.53+0000 lvl=dbug msg="using plugin" version=2
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:22:15.56+0000 lvl=dbug msg="Successfully started backend plugin process"
logger=plugin.manager t=2022-09-15T06:22:15.56+0000 lvl=info msg="Plugin registered" pluginId=vertamedia-clickhouse-datasource
logger=plugin.vertamedia-clickhouse-datasource t=2022-09-15T06:22:15.56+0000 lvl=dbug msg="starting plugin" path=/var/lib/grafana/plugins/vertamedia-clickhouse-datasource/altinity-clickhouse-plugin_linux_amd64 args="unsupported value type"
logger=plugin.manager t=2022-09-15T06:22:15.57+0000 lvl=eror msg="Could not start plugin" pluginId=vertamedia-clickhouse-datasource err="fork/exec /var/lib/grafana/plugins/vertamedia-clickhouse-datasource/altinity-clickhouse-plugin_linux_amd64: no such file or directory"
logger=secrets t=2022-09-15T06:22:15.57+0000 lvl=dbug msg="Envelope encryption state" enabled=false currentprovider=secretKey.v1
```

**Comment by Slach** [comment]
root reason
```
logger=plugin.manager t=2022-09-15T06:22:15.57+0000 lvl=eror msg="Could not start plugin" pluginId=vertamedia-clickhouse-datasource err="fork/exec /var/lib/grafana/plugins/vertamedia-clickhouse-datasource/altinity-clickhouse-plugin_linux_amd64: no such file or directory"
```

is not the same as you shared here

https://github.com/Altinity/clickhouse-grafana/issues/447#issuecomment-1246661267
```
bash-5.1$ ls -la /var/lib/grafana/plugins/vertamedia-clickhouse-datasource/
...
-rwxrwxr-x 1 grafana 472 21504577 Sep 8 08:35 altinity-clickhouse-plugin_linux_amd64
...
```


how you install plugins in kuberenetes?
do you use initContainers?

**Comment by devopscliff** [comment]
So firstly we have installed it via grafana-cli , but after your recent comment i have tried some other way to install it too !
I tried this way too :
![image](https://user-images.githubusercontent.com/106510107/190337627-025169d4-133e-4e32-bf88-66778c499130.png)

but still the same error presists there :

```
logger=plugin.loader t=2022-09-15T06:58:15.4+0000 lvl=dbug msg="Loading plugin" path=/var/lib/grafana/plugins/vertamedia-clickhouse-datasource/plugin.json
logger=plugin.loader t=2022-09-15T06:58:15.61+0000 lvl=dbug msg="Plugin signature valid" id=grafana-clickhouse-datasource
logger=plugin.loader t=2022-09-15T06:58:16.33+0000 lvl=dbug msg="Plugin signature valid" id=vertamedia-clickhouse-datasource
logger=plugin.signature.validator t=2022-09-15T06:58:16.33+0000 lvl=dbug msg="Plugin has valid signature" id=grafana-clickhouse-datasource
logger=plugin.signature.validator t=2022-09-15T06:58:16.33+0000 lvl=dbug msg="Plugin has valid signature" id=vertamedia-clickhouse-datasource
logger=plugin.manager t=2022-09-15T06:58:16.34+0000 lvl=info msg="Plugin registered" pluginId=grafana-clickhouse-datasource
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.34+0000 lvl=dbug msg="starting plugin" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64 args="unsupported value type"
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.34+0000 lvl=dbug msg="plugin started" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64 pid=36
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.34+0000 lvl=dbug msg="waiting for RPC address" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=info msg=Profiler enabled=false
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="Serving plugin" plugins="unsupported value type"
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="plugin address" address=/tmp/plugin657069086 network=unix
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="using plugin" version=2
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="Successfully started backend plugin process"
logger=plugin.manager t=2022-09-15T06:58:16.35+0000 lvl=info msg="Plugin registered" pluginId=vertamedia-clickhouse-datasource
logger=plugin.vertamedia-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="starting plugin" path=/var/lib/grafana/plugins/vertamedia-clickhouse-datasource/altinity-clickhouse-plugin_linux_amd64 args="unsupported value type"
logger=plugin.manager t=2022-09-15T06:58:16.35+0000 lvl=eror msg="Could not start plugin" pluginId=vertamedia-clickhouse-datasource err="fork/exec /var/lib/grafana/plugins/vertamedia-clickhouse-datasource/altinity-clickhouse-plugin_linux_amd64: no such file or directory"
logger=secrets t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="Envelope encryption state" enabled=false currentprovider=secretKey.v1
logger=accesscontrol.scoperesolution t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="adding attribute resolution for '%v'" datasources:name:=(MISSING)
logger=accesscontrol.scoperesolution t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="adding attribute resolution for '%v'" datasources:id:=(MISSING)
logger=query_data t=2022-09-15T06:58:16.36+0000 lvl=info msg="Query Service initialization"
logger=live t=2022-09-15T06:58:16.36+0000 lvl=dbug msg="GrafanaLive initialization" ha=false
```

**Comment by sdarshil** [comment]
So firstly we have installed it via grafana-cli , but after your recent comment i have tried some other way to install it too !
I tried this way too :
![image](https://user-images.githubusercontent.com/31997374/190338020-5e250284-5bf0-437d-a230-eb021be5614b.png)


but still the same error presists there :

logger=plugin.loader t=2022-09-15T06:58:15.4+0000 lvl=dbug msg="Loading plugin" path=/var/lib/grafana/plugins/vertamedia-clickhouse-datasource/plugin.json
logger=plugin.loader t=2022-09-15T06:58:15.61+0000 lvl=dbug msg="Plugin signature valid" id=grafana-clickhouse-datasource
logger=plugin.loader t=2022-09-15T06:58:16.33+0000 lvl=dbug msg="Plugin signature valid" id=vertamedia-clickhouse-datasource
logger=plugin.signature.validator t=2022-09-15T06:58:16.33+0000 lvl=dbug msg="Plugin has valid signature" id=grafana-clickhouse-datasource
logger=plugin.signature.validator t=2022-09-15T06:58:16.33+0000 lvl=dbug msg="Plugin has valid signature" id=vertamedia-clickhouse-datasource
logger=plugin.manager t=2022-09-15T06:58:16.34+0000 lvl=info msg="Plugin registered" pluginId=grafana-clickhouse-datasource
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.34+0000 lvl=dbug msg="starting plugin" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64 args="unsupported value type"
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.34+0000 lvl=dbug msg="plugin started" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64 pid=36
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.34+0000 lvl=dbug msg="waiting for RPC address" path=/var/lib/grafana/plugins/grafana-clickhouse-datasource/gpx_clickhouse_linux_amd64
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=info msg=Profiler enabled=false
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="Serving plugin" plugins="unsupported value type"
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="plugin address" address=/tmp/plugin657069086 network=unix
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="using plugin" version=2
logger=plugin.grafana-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="Successfully started backend plugin process"
logger=plugin.manager t=2022-09-15T06:58:16.35+0000 lvl=info msg="Plugin registered" pluginId=vertamedia-clickhouse-datasource
logger=plugin.vertamedia-clickhouse-datasource t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="starting plugin" path=/var/lib/grafana/plugins/vertamedia-clickhouse-datasource/altinity-clickhouse-plugin_linux_amd64 args="unsupported value type"
logger=plugin.manager t=2022-09-15T06:58:16.35+0000 lvl=eror msg="Could not start plugin" pluginId=vertamedia-clickhouse-datasource err="fork/exec /var/lib/grafana/plugins/vertamedia-clickhouse-datasource/altinity-clickhouse-plugin_linux_amd64: no such file or directory"
logger=secrets t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="Envelope encryption state" enabled=false currentprovider=secretKey.v1
logger=accesscontrol.scoperesolution t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="adding attribute resolution for '%v'" datasources:name:=(MISSING)
logger=accesscontrol.scoperesolution t=2022-09-15T06:58:16.35+0000 lvl=dbug msg="adding attribute resolution for '%v'" datasources:id:=(MISSING)
logger=query_data t=2022-09-15T06:58:16.36+0000 lvl=info msg="Query Service initialization"
logger=live t=2022-09-15T06:58:16.36+0000 lvl=dbug msg="GrafanaLive initialization" ha=false

**Comment by Slach** [comment]
Do you see anything in pod logs which ensure `GF_INSTALL_PLUGINS` works?

Something like  `Downloaded vertamedia-clickhouse-datasource v2.5.2 zip successfully` after startup grafana container

**Comment by sdarshil** [comment]
```
bash-5.1$ grafana-cli plugins ls
installed plugins:
grafana-clickhouse-datasource @ 2.0.1
vertamedia-clickhouse-datasource @ 2.5.2
[5:40](https://gtmhub.slack.com/archives/D03UY47DTFV/p1663243819162529)
```


Here i can see it is installed

**Comment by sdarshil** [comment]
![image](https://user-images.githubusercontent.com/31997374/190400449-a909575d-c494-4821-a794-d5ca83d0e5c0.png)

**Comment by Slach** [comment]
`ls -la /var/lib/grafana/plugins/vertamedia-clickhouse-datasource/altinity-clickhouse-plugin_linux_amd64` 
available after container start?
which kubernetes engine do you use?
look like similar with https://github.com/Altinity/clickhouse-grafana/issues/439#issuecomment-1224127815
check your seccomp \ apparmor profiles for kubernetes

**Comment by Slach** [comment]
Is issue still relevant for you? Or you found root reason?

**Comment by Slach** [comment]
another similar error message
```
{"err":"Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.","level":"error","logger":"plugin.manager","msg":"Could not start plugin","pluginId":"vertamedia-clickhouse-datasource","t":"2022-10-04T09:19:24.919726963Z"}
```

need to new release with latest sdk
