### ISSUE TITLE
Grafana `Stacking and null value` Bug

### ISSUE THREAD

**Issue by frank-lam** [Altinity/clickhouse-grafana#448]
Grafana v7.5.11
`Display` -> `Stacking and null value` -> `null as zero`

When I use the clickhouse grafana plug-in to query SQL, when the data points are empty, the "Stacking and null value" -> "null as zero" is not work, plug-in connects the data points by default.

This is very impersonal.

**Comment by Slach** [comment]
Plugin doesn't provide any vizualization itself

Then you don't have data point, you really don't have data, if you expect `null`
use `ORDER BY ... WITH FILL `
look details 
https://clickhouse.com/docs/en/sql-reference/statements/select/order-by/#order-by-expr-with-fill-modifier
