### ISSUE TITLE
Support for delta calculation

### ISSUE THREAD

**Issue by oplehto** [Altinity/clickhouse-grafana#455]
It would be nice if there would be variants of the per-second macros for delta calculations as well. Basically the same macro but without normalizing by the time step length.

**Comment by Slach** [comment]
i thin it could be implements easy

**Comment by Slach** [comment]
i will implements 4 macros
$increase, $increaseColumns - for non negative delta calcuation
and
$delta, $deltaCoumns - for delta calculation with negative
