### ISSUE TITLE
Question: Is possible to check for specific variable value in during query building.

### ISSUE THREAD

**Issue by ceckoslab** [Altinity/clickhouse-grafana#457]
I read the plugin docs and played a lot with the plugin but I couldn't find a way to make this working.

Here is my case:

I am building dashboards for displaying webperformance metrics. Depending on a metric sometimes the SQL is slightly different.

This is the query for a metric called Cumulative Layout Shift:
```
SELECT
    intDiv(cumulative_layout_shift, 0.01) * 0.01 as cumulative_layout_shift,
    sum(toUInt32(1)) as count
    
FROM $table

WHERE
    $timeFilter
    AND event_type = 'visit_page'
    AND cumulative_layout_shift IS NOT NULL
    $conditionalTest(AND hostname in($hostname), $hostname)

GROUP BY cumulative_layout_shift
ORDER BY cumulative_layout_shift
```

Here we have another for Time to First Byte:
```
SELECT
    intDiv(first_byte_duration, $bucket_size) * $bucket_size as first_byte_duration_value,
    sum(toUInt64(1)) as count
    
FROM $table

WHERE
    $timeFilter
    AND $perf_timer > 100
    AND $perf_timer < 10000
    AND event_type = 'visit_page'
    $conditionalTest(AND hostname in($hostname), $hostname)

GROUP BY first_byte_duration_value
ORDER BY first_byte_duration_value
```

The example queries have some differences:
 * The Cumulative Layout Shift query has a check for NOT NULL.
 * The Cumulative Layout Shift  also has different bucketing: `intDiv(cumulative_layout_shift, 0.01) * 0.01 as cumulative_layout_shift`
 
 Is it possible to have something similar in the query temple:
 
```
$variableMatch('cumulative_layout_shift', $perf_timer, 
SELECT
    intDiv(cumulative_layout_shift, 0.01) * 0.01 as cumulative_layout_shift,
    sum(toUInt32(1)) as count
    
FROM $table

WHERE
    $timeFilter
    AND event_type = 'visit_page'
    AND cumulative_layout_shift IS NOT NULL
    $conditionalTest(AND hostname in($hostname), $hostname)

GROUP BY cumulative_layout_shift
ORDER BY cumulative_layout_shift
)

$variableMatch('first_byte_duration', $perf_timer, 
SELECT
    intDiv(first_byte_duration, $bucket_size) * $bucket_size as first_byte_duration_value,
    sum(toUInt64(1)) as count
    
FROM $table

WHERE
    $timeFilter
    AND $perf_timer > 100
    AND $perf_timer < 10000
    AND event_type = 'visit_page'
    $conditionalTest(AND hostname in($hostname), $hostname)

GROUP BY first_byte_duration_value
ORDER BY first_byte_duration_value
)
```

**Comment by Slach** [comment]
sorry, i don't understand

what exactly SQL shall generated after apply
```
$variableMatch('cumulative_layout_shift', $perf_timer,
```
?

could you provide raq SQL which you want to generate?

**Comment by ceckoslab** [comment]
Sorry, I had to be more specific. I will try again :) 

It's something like a SWITCH operator.

If **$perf_timer** value is **cumulative_layout_shift** I would like to get the query wrapped only in this block:
```
$variableMatch('cumulative_layout_shift', $perf_timer, 
SELECT
    intDiv(cumulative_layout_shift, 0.01) * 0.01 as cumulative_layout_shift,
    sum(toUInt32(1)) as count
    
FROM $table

WHERE
    $timeFilter
    AND event_type = 'visit_page'
    AND cumulative_layout_shift IS NOT NULL
    $conditionalTest(AND hostname in($hostname), $hostname)

GROUP BY cumulative_layout_shift
ORDER BY cumulative_layout_shift
)
```

So if we have this save in the Gafana query editor:
```
$variableMatch('cumulative_layout_shift', $perf_timer, 
SELECT
    intDiv(cumulative_layout_shift, 0.01) * 0.01 as cumulative_layout_shift,
    sum(toUInt32(1)) as count
    
FROM $table

WHERE
    $timeFilter
    AND event_type = 'visit_page'
    AND cumulative_layout_shift IS NOT NULL
    $conditionalTest(AND hostname in($hostname), $hostname)

GROUP BY cumulative_layout_shift
ORDER BY cumulative_layout_shift
)

$variableMatch('first_byte_duration', $perf_timer, 
SELECT
    intDiv(first_byte_duration, $bucket_size) * $bucket_size as first_byte_duration_value,
    sum(toUInt64(1)) as count
    
FROM $table

WHERE
    $timeFilter
    AND $perf_timer > 100
    AND $perf_timer < 10000
    AND event_type = 'visit_page'
    $conditionalTest(AND hostname in($hostname), $hostname)

GROUP BY first_byte_duration_value
ORDER BY first_byte_duration_value
)
```

I would like to get as a RAW SQL:
```
SELECT
    intDiv(cumulative_layout_shift, 0.01) * 0.01 as cumulative_layout_shift,
    sum(toUInt32(1)) as count
    
FROM performance_data_table

WHERE
    event_date >= toDate(1661176376) AND event_date <= toDate(1668955976) AND created_at >= toDateTime(1661176376) AND created_at <= toDateTime(1668955976)
    AND event_type = 'visit_page'
    AND cumulative_layout_shift IS NOT NULL
    AND hostname IN('www.myhost.com')

GROUP BY cumulative_layout_shift
ORDER BY cumulative_layout_shift
```

If **$perf_timer** value is **first_byte_duration** I would like to get this RAW SQL:
```
SELECT
    intDiv(first_byte_duration, 100) * 100 as first_byte_duration_value,
    sum(toUInt64(1)) as count
    
FROM performance_data_table

WHERE
    event_date >= toDate(1661176376) AND event_date <= toDate(1668955976) AND created_at >= toDateTime(1661176376) AND created_at <= toDateTime(1668955976)
    AND first_byte_duration > 100
    AND first_byte_duration < 10000
    AND event_type = 'visit_page'
    AND hostname IN('www.myhost.com')

GROUP BY first_byte_duration_value
ORDER BY first_byte_duration_value
```

**Comment by Slach** [comment]
Ok. I would like to propose create TWO separate queries

and add 
`AND $perf_timer = 'cumulative_layout_shift'` to first query


`AND $perf_timer = 'first_byte_duration`` to second query

**Comment by ceckoslab** [comment]
Is the proposal to always run the TWO queries in parallel for the same panel? 

The queries will be more different in the WHERE clause but also the SELECT part varies.

For **cumulative_layout_shift** we have bucketing by `0.01` where for **first_byte_duration** we have bucketing by `100`.

For cumulative_layout_shift:
```
SELECT
    intDiv(cumulative_layout_shift, 0.01) * 0.01 as cumulative_layout_shift,
    sum(toUInt32(1)) as count
```

For first_byte_duration:
```
SELECT
    intDiv(first_byte_duration, 100) * 100 as first_byte_duration_value,
    sum(toUInt64(1)) as count
```

By the way, I've never written a single line for a Grafana plugin but I would like to contribute if such a thing makes sense or if it already doesn't exist out of the box.

**Comment by Slach** [comment]
any PR is welcome ;)

**Comment by Slach** [comment]
query where `AND false` will fast

**Comment by ceckoslab** [comment]
One more clarification. My intention is to show display the result in single Grafana panel.

**cumulative_layout_shift**
![Screenshot from 2022-11-21 15-01-04](https://user-images.githubusercontent.com/1024001/203074082-97b0fb4c-e4d7-4e7e-8731-d1048221fc4d.png)

**first_byte_duration**
![Screenshot from 2022-11-21 15-01-16](https://user-images.githubusercontent.com/1024001/203074145-9ddb8e1a-42c7-4af8-82d0-8cacb566e788.png)

The bucketing and filtering for these metrics is different and that's why all the complexity. I already have the metrics rendered in separate Grafana panels but for some dashboards I would like to have metrics to be rendered in a single Grafana panel. The querying and rendered data in the panel will triggered by selecting an option from a filter.

E.g.
![Screenshot from 2022-11-21 15-06-37](https://user-images.githubusercontent.com/1024001/203075107-44c43386-f05b-48bb-9789-aa1d5c6ddf24.png)

I think that we can close this issue.

**Comment by ceckoslab** [comment]
@Slach I just opened this PR: https://github.com/Altinity/clickhouse-grafana/pull/466

My intention is to socialize the idea/intention.

**Comment by Slach** [comment]
close after long inactivity
