### ISSUE TITLE
"No Data" when using Subquery

### ISSUE THREAD

**Issue by fionera** [Altinity/clickhouse-grafana#464]
Hi. I hope this is a Bug and not me being bad with Clickhouse Queries. I try to optimize the queries I use in a Grafana Dashboard right now and I have some issues with it. 

This Query works but is very slow because it groups on the string:
```
SELECT
        (intDiv(toUInt32(TimeReceived), 2) * 2) * 1000 AS t,
        sum(Packets * SamplingRate) / 2 AS Packets,
        if(FlowDirection = 1, 'out', 'in') AS FlowDirectionStr
FROM flows_raw
WHERE (TimeReceived >= toDateTime(1670976803)) AND (TimeReceived <= toDateTime(1670978603))
GROUP BY
    t,
    FlowDirectionStr
ORDER BY t ASC
```

When I wrap all data aggregation into a subquery and move the lookups into the outer query the grafana panel shows "no data":
```
SELECT
    t,
    Packets,
    if(FlowDirection = 1, 'out', 'in') AS FlowDirectionStr
FROM
    (
        SELECT
                (intDiv(toUInt32(TimeReceived), 2) * 2) * 1000 AS t,
                sum(Packets * SamplingRate) / 2 AS Packets,
                FlowDirection
        FROM flows_raw
        WHERE (TimeReceived >= toDateTime(1670976803)) AND (TimeReceived <= toDateTime(1670978603))
        GROUP BY
            t,
            FlowDirection
        ORDER BY t ASC
        )
GROUP BY
    t,
    Packets,
    FlowDirectionStr
```

Even when I only do a simpel SELECT * FROM (SELECT... it doesnt work and lists the columns as different data points.
```
SELECT
    *
FROM
    (
        SELECT
                (intDiv(toUInt32(TimeReceived), 2) * 2) * 1000 AS t,
                sum(Packets * SamplingRate) / 2 AS Packets,
                FlowDirection
        FROM flows_raw
        WHERE (TimeReceived >= toDateTime(1670976803)) AND (TimeReceived <= toDateTime(1670978603))
        GROUP BY
            t,
            FlowDirection
        ORDER BY t ASC
        )
```

Thank you :)

**Comment by Slach** [comment]
try to swap `Packets` and `FlowDirectionStr`
```sql
SELECT
        (intDiv(toUInt32(TimeReceived), 2) * 2) * 1000 AS t,
        if(FlowDirection = 1, 'out', 'in') AS FlowDirectionStr,
        sum(Packets * SamplingRate) / 2 AS Packets
FROM flows_raw
WHERE $timeFilter
GROUP BY
    t,
    FlowDirectionStr
ORDER BY t ASC
```

**Comment by fionera** [comment]
The Issue is that I want to not group by FlowDirectionStr. Instead I want to group on FlowDirection and then replace it after the aggregation.

The original Query with group by FlowDirectionStr looks like this:
![Screenshot_20221214_150905](https://user-images.githubusercontent.com/5741401/207616950-533ee3d5-b812-4e0e-b622-11b458851675.png)
```
SELECT
    (intDiv(toUInt32(TimeReceived), 5) * 5) * 1000 as t,
    sum(Packets * SamplingRate) / 5 AS Packets,
    if(FlowDirection == 1, 'out', 'in') AS FlowDirectionStr
FROM flows_raw
WHERE TimeReceived >= toDateTime(1671016216) AND TimeReceived <= toDateTime(1671027016)
GROUP BY t, FlowDirectionStr
ORDER BY t
```

---


Even with moving around the select order it looks like this:
![Screenshot_20221214_150838](https://user-images.githubusercontent.com/5741401/207616859-73757e3b-0cae-4e6c-8200-e01f55f333a9.png)

```
SELECT 
t, 
Packets, 
if(FlowDirection = 1, 'out', 'in') AS FlowDirectionStr 
FROM (
SELECT
    (intDiv(toUInt32(TimeReceived), 5) * 5) * 1000 as t,        
        sum(Packets * SamplingRate) / 2 AS Packets,
        FlowDirection
FROM flows_raw
WHERE TimeReceived >= toDateTime(1671016032) AND TimeReceived <= toDateTime(1671026832)
GROUP BY t, FlowDirection
ORDER BY t)
```

**Comment by Slach** [comment]
did you try
```sql
SELECT 
t, 
if(FlowDirection = 1, 'out', 'in') AS FlowDirectionStr,
Packets

FROM (
SELECT
    (intDiv(toUInt32(TimeReceived), 5) * 5) * 1000 as t,        
        sum(Packets * SamplingRate) / 2 AS Packets,
        FlowDirection
FROM flows_raw
WHERE $timeFilter
GROUP BY t, FlowDirection
ORDER BY t
)
```

**Comment by Slach** [comment]
do you need summing aggregate Packets for FlowDirectionStr?

**Comment by fionera** [comment]
No that also does not work and results in this:
![Screenshot_20221214_152859](https://user-images.githubusercontent.com/5741401/207622264-507552b5-551b-4faa-8e3c-eb6ba8ac937b.png)

I want to know the amount of packets per FlowDirection, yes

**Comment by Slach** [comment]
> I want to know the amount of packets per FlowDirection, yes

according to your SQL queries
FlowDirection could be `1,2,3, -1`
but 
FlowDirectionStr only 'in', 'out'

Do you need different series Packets for each `FlowDirection` or `FlowDirectionStr`?

**Comment by fionera** [comment]
FlowDirection is a UInt8 and can be everything between 0 and 255. FlowDirectionStr should be 'out' when FlowDirection == 1, else it should be 'in'. With multiple select parameters it works but that is not always possible.

There are also other cases of this issue where I cannot replace it with multiple select parameters. Thats why I think this is a Bug :)

**Comment by Slach** [comment]
> With multiple select parameters it works but that is not always possible.

what exactly means "multiple select paramaters"?

> Thats why I think this is a Bug :)

This is definitely not a bug ;)

just try https://github.com/Altinity/clickhouse-grafana/issues/464#issuecomment-1351517952
or try
```sql
$columns( if(FlowDirection = 1, 'out', 'in') AS FlowDirectionStr,  sum(Packets * SamplingRate) AS Packets )
FROM $table
WHERE $timeFilter
```

**Comment by fionera** [comment]
This still the same issue. I want to have a SELECT in a Subquery where I do lookups in the parent Query. When I use $columns it will group on the looked up value and that is very slow. The Solution in https://github.com/Altinity/clickhouse-grafana/issues/464#issuecomment-1351517952 only works on this specific Query. I do also have other Queries where I group on the raw value and have a lookup in the select

**Comment by Slach** [comment]
Parsable formats 

1)
first field UInt64 in ms
second field String // field value will use as label for time series name
third field numeric 

2) first field UInt64 in ms
second field numeric
...
N field numeric // field name will series name

3)
first field UInt64 in ms
second field array of tuples each 0 elements string (label) 1 element numeric (value)
