### ISSUE TITLE
Grafana Alerting： "failed to execute conditions: [plugin.unavailable] plugin unavailable" 

### ISSUE THREAD

**Issue by OPSTime** [Altinity/clickhouse-grafana#465]
grafana version: 9.2.5

**grafana log:**
`logger=ngalert rule_uid=WZdym5p4k org_id=1 version=1 attempt=0 now=2022-12-27T08:22:00Z t=2022-12-27T08:22:00.058174179Z level=error msg="failed to evaluate alert rule" results="[{Instance: State:Error Error:failed to execute conditions: [plugin.unavailable] plugin unavailable EvaluatedAt:2022-12-27 08:22:00 +0000 UTC EvaluationDuration:58.16998ms EvaluationString: Values:map[]}]" duration=39.662198ms`

**Looks like it's related to the clickhouse plugin：**
```
  plugins:
    allow_loading_unsigned_plugins: vertamedia-clickhouse-datasource
```

![alert error1](https://user-images.githubusercontent.com/5848331/209781828-9cf8506d-08a0-42f4-8f4e-f07d4979458b.png)

![alert error2](https://user-images.githubusercontent.com/5848331/209781848-574e119e-64ab-4b17-8d2f-fe1601950862.png)

**Comment by OPSTime** [comment]
The plug-in version is too old.

**Comment by Slach** [comment]
Could you confirm, is the latest version of plugin works?

**Comment by OPSTime** [comment]
Thx. Please ignore the problem. I have updated the plug-in to the latest version.
