### ISSUE TITLE
Angular is deprecated - please migrate to React

### ISSUE THREAD

**Issue by tolzhabayev** [Altinity/clickhouse-grafana#475]
# Hello :wave: from Grafana Labs

We have detected that your plugin might still be using `AngularJS` and recommend migrating it to `React`, so that it may continue to operate successfully in future versions of Grafana.

You can read more on why and how by visiting our documentation: https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

You can reach out to us with any questions via slack: [slack.grafana.com](https://slack.grafana.com) - channel `#plugins` or our [plugin development community forum](https://community.grafana.com/c/plugin-development/30)

**Comment by Slach** [comment]
@tolzhabayev we submitted to grafana.com 
new release, https://github.com/Altinity/clickhouse-grafana/releases/tag/v3.0.0

Which is not contained any angular dependencies, why `grafana` still show Angular warning for plugin?

Is the Angular mark is manual from Grafana Labs side?

**Comment by tolzhabayev** [comment]
@Slach can you specify which one of the messages you mean / where you see it? We have a lot of different places where we flag plugins as angular and some are based on code detection and some on fetching data from our APIs that have a list of plugin versions that we update. 

Generally - great news and thank you for doing the work and migrating!

**Comment by Slach** [comment]
@tolzhabayev 
just open my local plugin installation
http://localhost:3000/plugins/vertamedia-clickhouse-datasource
3.0.0 have no angular dependencies and created from scratch with React
![image](https://github.com/Altinity/clickhouse-grafana/assets/105560/9018cfdf-1415-4ea4-ba24-d203321901d7)

**Comment by tolzhabayev** [comment]
@Slach it is interesting as I don't see this banner if I just checkout your latest master, build and run the `npm run server`

**Comment by Slach** [comment]
@tolzhabayev 3.0.0 was released yesterday, and now clickhouse-grafana altinity plugin just not marked as angular

**Comment by tolzhabayev** [comment]
awesome! thanks for doing the work
