### ISSUE TITLE
Relationship between this one and the official plugin?

### ISSUE THREAD

**Issue by fzyzcjy** [Altinity/clickhouse-grafana#482]
Hi thanks for the datasource! However, I realize there seem to be an official plugin: https://grafana.com/grafana/plugins/grafana-clickhouse-datasource So I wonder which one should I use?

**Comment by Slach** [comment]
This is separate project.
We continue develop it from 2017.
Official plugin developed from 2021.

Just compare with official plugin and use what do you wish.
