### ISSUE TITLE
Configured custom headers not being used in Grafana managed alerts

### ISSUE THREAD

**Issue by johnspurlock** [Altinity/clickhouse-grafana#483]
Hi there, great plugin!  I have a configured datasource that needs to specify a custom `Authorization` header.  This is working well in multiple dashboards.

![image](https://github.com/Altinity/clickhouse-grafana/assets/528937/5604deef-f443-4ec6-9d60-6f7710f76f82)

I'd like to use this datasource in Grafana's alert feature, but all queries fail!  Seemingly not using the custom header for alerts.

<img width="614" alt="image" src="https://github.com/Altinity/clickhouse-grafana/assets/528937/e453881c-e89c-4d1d-a516-1056462389f7">

Grafana v10.0.0 (81d85ce802)
plugin version: 2.5.3

**Comment by Slach** [comment]
looks like bug in golang part of plugin

**Comment by johnspurlock** [comment]
Ah ok, thanks for taking a look

**Comment by lopis** [comment]
Hello. I've been running into this same issue. Did you ever find a workaround?

**Comment by johnspurlock** [comment]
No workaround in the plugin unfortunately - I ended up making a proxy datasource

Hoping to see this in the plugin at some point!

**Comment by addshore** [comment]
I also just experienced this issue on Grafana cloud while using this plugin to access data from Cloudflare worker analytics.

> looks like bug in golang part of plugin

Got a pointer to where? :)

**Comment by addshore** [comment]
Aaah perhaps https://github.com/Altinity/clickhouse-grafana/blob/ab4ccd85bd01622cf405207cdb9625b2436cb180/pkg/datasource_settings.go#L12 relates to this

Headers on requests are currently set in this section https://github.com/Altinity/clickhouse-grafana/blob/ab4ccd85bd01622cf405207cdb9625b2436cb180/pkg/client.go#L61-L78

And I see nothing about custom headers there
