### ISSUE TITLE
Ability to set a default column names for the primary time column in the datasource config. for Date and Timestamp, This would be used by the $timeFilter etc. macros unless overridden in the query builder

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-grafana#495]
add to ConfigEditor
- datetime
- datetime64
- uint32
- date / date32

**Comment by oplehto** [comment]
What would be really fantastic would be to able to define multiple default time columns which could be used in order of precedence. 

For example, if the config has `_time, _time64` as default time columns then the `_time` column would be used if found (and is a suitable type). If not, then `_time64` would be searched for. In case both columns are present, then the first one in the list would be used.

**Comment by Slach** [comment]
> What would be really fantastic would be to able to define multiple default time columns which could be used in order of precedence.

@oplehto 
No, it will define only only one field for each related field type per connection
