### ISSUE TITLE
alert metric name problem

### ISSUE THREAD

**Issue by myshzzx** [Altinity/clickhouse-grafana#499]
![image](https://github.com/Altinity/clickhouse-grafana/assets/2025090/30ec7fff-c375-4de9-b342-7279294d1c2b)

my sql looks like 
`select time, metric, count() from xx group by time,metric`

and show like 
![image](https://github.com/Altinity/clickhouse-grafana/assets/2025090/db98279a-d834-489c-9620-aea569b2a93a)

then I add an alert , and get notice like this 
![image](https://github.com/Altinity/clickhouse-grafana/assets/2025090/92d47bfc-d7f1-4cff-9cf1-8d995ff7b284)

**Comment by Slach** [comment]
duplicated with previous issue
try follow suggestion here https://github.com/Altinity/clickhouse-grafana/issues/498#issuecomment-1829409212

**Comment by Slach** [comment]
try to following query
```sql
SELECT
    t,
    groupArray((metric, cnt)) AS groupArr
FROM (
  select time AS t, metric, count() cnt from xx group by t,metric
)
GROUP BY t
ORDER BY t
```
