### ISSUE TITLE
Ad-hoc filters - error when evaluating varchar field with numeric value

### ISSUE THREAD

**Issue by afagundes** [Altinity/clickhouse-grafana#502]
We discovered a potential problem in the ad-hoc filters where fields of type varchar containing numeric values are assessed as numbers. The values are appended to the final query without quotation marks, resulting in the following error:

<img width="1310" alt="Captura de Tela 2023-12-11 às 11 06 59" src="https://github.com/Altinity/clickhouse-grafana/assets/7586824/8014eabd-b4d8-4c36-82b7-044798c89bf9">

This particular field is a `LowCardinality(String)` whose values are something like '1', '1000' or 'C'.

Investigating the source code, I found this line that casts numeric values:

<img width="859" alt="image" src="https://github.com/Altinity/clickhouse-grafana/assets/7586824/ecc30fe6-4c77-475c-92cf-ba7dc3b62b58">

when I change the code to treat all values as strings, all filters work as expected.

<img width="859" alt="image" src="https://github.com/Altinity/clickhouse-grafana/assets/7586824/6fb346f5-d91e-4db9-b028-68885f73f26d">

I'm not sure if this is the best approach, since it forces Clickhouse to do the conversion. But in my tests I didn't feel any performance issues.

If it's ok, I'll submit a pull request with the change.

**Comment by Slach** [comment]
sorry =) look like you found issue in https://github.com/grafana/clickhouse-datasource/, but this is different plugin, please clarify, do you use Altinity ClickHouse plugin for Grafana or Grafana ClickHouse Datasource?

**Comment by afagundes** [comment]
Hi @Slach. Apologies, I opened this issue in the wrong project. I'll close it now and open a new one in the correct repository. Thanks!

**Comment by afagundes** [comment]
Hi @Slach. Apologies, I opened this issue in the wrong project. I'll close it now and open a new one in the correct repository. Thanks!
