### ISSUE TITLE
Grafana Cloud Support

### ISSUE THREAD

**Issue by chrishubert** [Altinity/clickhouse-grafana#516]
I have been using the plugin in the previous "AngularJS" version without any problem to visualize my Cloudflare Analytics data in [Grafana Cloud](https://grafana.com/products/cloud/ )
After being prompted by Grafana to update, I blindly went for it and I can't seem to make it working.
- I tried Uninstall / Re-Install version 3.0.0 without success
- There are no settings showing (the console doesn't give any relevant error)
![image](https://github.com/Altinity/clickhouse-grafana/assets/8528436/27a50d48-284d-46be-b28a-c9653f4dbcc8)

Did I miss something? Am I the only facing this issue?
This plugin is the only one that seems to work with Cloudflare Analytics, so I'm a bit desperate to make it work.

**Comment by Slach** [comment]
Did you try ask help in Grafana Cloud team?

**Comment by chrishubert** [comment]
> Did you try ask help in Grafana Cloud team?

I'll do that right away as well

**Comment by chrishubert** [comment]
Some progress:

We can see the settings now
But the dataSourceUrl is now read only, and we can't enter anything there, ticket still ongoing.
```
An unexpected error happened
Details
TypeError: Cannot assign to read only property 'dataSourceUrl' of object '[object Object]'
```

**Comment by Slach** [comment]
Which Grafana server version do you use?

**Comment by chrishubert** [comment]
> Which Grafana server version do you use?

Grafana Cloud seems to be running with `Grafana v10.4.0-66955 (556d531c8d)`

**Comment by jamckelvey** [comment]
I am having the same issue you mentioned above, no settings. How did you get the settings to even show up?

**Comment by ShravanSunder** [comment]
@Slach 
i think the issue with https://github.com/Altinity/clickhouse-grafana/issues/517 is slightly different.  

I had to force reload to get the settings to show up.  you have to update grafana cloud from a different page to https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/ to make sure your isntance has the latest plugin first.  if you click get plugin in this screen it allows you ot update it.   Then you have to force reload the settings (clear cache).

The issue in https://github.com/Altinity/clickhouse-grafana/issues/517 is actually an issue with the plugin

**Comment by chrishubert** [comment]
@jamckelvey, use hard refresh (CTRL+SHIFT+R) to display the settings.
I still get the same error though. But I managed somehow to save the URL. in the datasource.

This is the response from the support ticket:

> Thanks for the update. I took a look, and this is likely an issue with the plugin itself, as the plugin configures these form inputs. Since this is a third-party plugin, support has limited visibility into the inner workings. At this point, I suggest reaching out to the plugin developer. 

I agree that it seems to be the same issue as https://github.com/Altinity/clickhouse-grafana/issues/517

**Comment by Cherry** [comment]
For some additional context on the settings, the Grafana Cloud had to downgrade my Cloud instance to v10, and enable the Angular support flag. Previously, it was running some test version of 11, which I imagine they do for testing updates with Cloud users.

I did still run into https://github.com/Altinity/clickhouse-grafana/issues/517 (resolved by manually hitting API), as well as another issue that prevented me from setting the DateTime field in a query (resolved by manually editing JSON), as well as the "Format As" to "Table" (also solved by manually editing the JSON).

**Comment by Slach** [comment]
Guys thanks for reporting, will try fix it ASAP, 
issue from https://github.com/Altinity/clickhouse-grafana/issues/517

related with our workaround for pass
https://github.com/grafana/grafana/pull/80858

we applied workaround with `datasourceUrl`, but looks like it broken on grafana 10.4

**Comment by Slach** [comment]
@chrishubert could you create a separate issue what exactly doesn't work with `Format As`?
we already have https://github.com/Altinity/clickhouse-grafana/issues/515, don't be shy to add your feedback in this issue
