### ISSUE TITLE
No longer possible to specify custom timestamp column value in 3.0.0 

### ISSUE THREAD

**Issue by fnewberg** [Altinity/clickhouse-grafana#529]
It used to be possible to specify a custom value rather than a column in the table as the timestamp value, but this seems to no longer be possible in 3.0.0. Previously I could specify that the timestamp should be computed from an `hour` column, but this no longer gets saved when I try to specify it. 

<img width="624" alt="image" src="https://github.com/Altinity/clickhouse-grafana/assets/209386/08be5427-87a9-4b6e-9634-5d44b2c5b1c0">

This then in turn breaks the $timeFilter and $timeSeries macros

```
SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t
```

becomes

```
SELECT
    (intDiv(toUInt32(undefined), 10) * 10) * 1000 as t,
    count()
FROM session.session_version

WHERE
    date >= toDate(1711124831)
    AND date <= toDate(1711146431)
    AND undefined >= toDateTime(1711124831)
    AND undefined <= toDateTime(1711146431)
GROUP BY t

ORDER BY t
```

not presence of `undefined` in 3 places

**Comment by Slach** [comment]
as quick workaround could you try
```
SELECT $timeSeries(toDateTime(hour*3600)) as t, count() FROM $table WHERE $timeFilter(toDateTime(hour*3600)) GROUP BY t ORDER BY t
```
but not sure will it work or not
