### ISSUE TITLE
Broken table with specific query in 3.0.0

### ISSUE THREAD

**Issue by danipozo** [Altinity/clickhouse-grafana#533]
The following query:
```sql
SELECT
  level,
  ngramSimHash(message_format_string) as format_hash,
  arrayJoin(groupArraySample(${nsamples})(message)) as message
FROM merge(system, 'text_log*') 
WHERE ( 
  event_time >= $from 
    AND 
  event_time <= $to )
GROUP BY level, message_format_string LIMIT 1000
```
renders a broken table:
![image](https://github.com/Altinity/clickhouse-grafana/assets/15173583/875bd95b-b68a-4091-b96f-32c75822f9fb)
I cannot get rid of the "Time" column even if I set "Format as" to "Table" (and also I have other tables working fine without that setting). I haven't been able to reproduce this in any other way or find out what about this query is breaking the frontend. Feel free to ask for logs or anything that may be useful to debug.

Another failure mode. This query:
```sql
SELECT
  event_time,
  level,
  ngramSimHash(message_format_string) as format_hash,
  arrayJoin(groupArraySample(${nsamples})(message)) as message
FROM merge(system, 'text_log*') tl
WHERE ( 
  event_time >= $from 
    AND 
  event_time <= $to )
GROUP BY 1, level, message_format_string LIMIT 1000
```
renders as:
![image](https://github.com/Altinity/clickhouse-grafana/assets/15173583/682a044c-3cc3-40e8-9f21-fde2860ee025)

**Comment by Slach** [comment]
Could you try the same queries in latest 2.x plugin version and share screenshots?

**Comment by danipozo** [comment]
It works correctly in 2.5.4 setting "Format as" to table:
![image](https://github.com/Altinity/clickhouse-grafana/assets/15173583/e234edd7-d6a6-4292-ab0e-e28e519ef513)

**Comment by Slach** [comment]
could be duplicated with https://github.com/Altinity/clickhouse-grafana/issues/515
will try to reproduce with master branch locally

**Comment by Slach** [comment]
> It seems to be working in master in my own local tests. Just to know, when is a minor release expected?

soon as possible

**Comment by danipozo** [comment]
> soon as possible

Thanks! Closing this issue since it is fixed in the pre-releases.
