### ISSUE TITLE
SQL Query Reset Issue in Panels with Multiple Clickhouse Altinity Datasources

### ISSUE THREAD

**Issue by LeThaumaturge** [Altinity/clickhouse-grafana#604]
**Description:**

Hello,

I am encountering an issue with the Clickhouse-Grafana plugin when editing a panel that includes multiple Clickhouse Altinity datasources in mixed mode.

**Observed Behavior:**

When I edit a panel with multiple Clickhouse Altinity datasources, the SQL query for the first datasource is consistently reset to the following default content: `SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t`

This is problematic because it's easy to lose custom configurations if not careful.

**Steps to Reproduce the Issue:**

- Create two Clickhouse datasources in the Data Sources section with the Altinity plugin for ClickHouse (datasourceA and datasourceB, for example).
- Create a dashboard including a panel using mixed datasources.
- Add the two Altinity datasources (datasourceA and datasourceB) with their own configurations.
- Save the dashboard.
- Reload the dashboard.
- Edit the panel without making any changes and cancel via "discard".
- After these steps, the first query will be reset, which is not the expected behavior. If you click on save, you will see in the incoming changes.

Note: There is no problem if you use the same datasource twice (datasourceA and datasourceA).
Note 2 : There is no problem with previous major version (version 2.5.4 is fine). 

**Expected Behavior:**

The SQL query for each datasource should remain unchanged after editing the panel unless explicit modifications are made.

**Additional Information:**

Grafana Version: 10.3.6
Clickhouse Plugin Version: 3.2.1 (latest)
Browser: 6.8.3381.50 (Stable channel) (arm64) 

Best regards,

**Comment by Slach** [comment]
Thank you so much for reporting, could you make a screencast with wrong behavior to better understanding?

@antip00 could we make e2e test for this scenario?

**Comment by LeThaumaturge** [comment]
@Slach for sure.

https://github.com/user-attachments/assets/3db6b3cb-7cf8-4c7b-9137-8a71d2f6c85a

**Comment by LeThaumaturge** [comment]
@Slach for sure. Here is an example :

https://github.com/user-attachments/assets/fb2ffc78-1b9d-41ff-8d82-521c754e983d

**Comment by LeThaumaturge** [comment]
@Slach for sure, here is an example : 

https://github.com/user-attachments/assets/6fd139a4-4cde-4751-a20b-292f376b4adb

note: sorry for multiple updates, I had to modify attachment.
