### ISSUE TITLE
Support for DateTime([timezone]) time fields consistently

### ISSUE THREAD

**Issue by oplehto** [Altinity/clickhouse-grafana#625]
It seems like in certain cases DateTime values with a timezone i.e. (`DateTime('America/Chicago')`) are not considered valid. For basic timeseries and tables they work but in some cases they fail. 

Examples that I found:
 - Timestamp column for the logs panel
 - Lookup of default timestamp values. Fix here should be as easy as adjusting this query with something like`splitByChar('(',type)[1] AS type`?. At the same time it could be optimized with a `GROUP BY type, name` to return only distinct values https://github.com/Altinity/clickhouse-grafana/blob/a521a079439f2a051b6fec886a41faef936d26c9/src/views/ConfigEditor/FormParts/DefaultValues/DefaultValues.tsx#L5

There are probably other situations as well. Seems like some type matching is happening where only `DateTime` and `DateTime64(N)` are considered timestamps.

While doing this it should be ensured that the timezone-enabled timestamps work correctly and do not get skewed (i.e. timezone shift done twice accidentally so a GMT+4 becomes GMT+8)

**Comment by Slach** [comment]
dropdown should be fixed in https://github.com/Altinity/clickhouse-grafana/pull/633/commits/6ea625b6e8506509c8fbd47cf6b1f6055d4ef4ef

**Comment by oplehto** [comment]
An example here would be the timestamp column for the **logs** panel (in the logs mode) as I mentioned in the issue. I assume you are testing with a Graph or Table panel?

I think it's due to the very specific matching done here for the column type: https://github.com/Altinity/clickhouse-grafana/blob/0ad4543679bc2d4c0d0587d458c6d3e91499392a/src/datasource/sql_series.ts#L474-L484

There may be issues with other panel types as well. I didn't look. Hence this request to review that the timestamp with timezone support is comprehensive meaning all the panel types support it.
