### ISSUE TITLE
Support for float, decimal and *Int64 timestamp for logs

### ISSUE THREAD

**Issue by oplehto** [Altinity/clickhouse-grafana#626]
In the logs panel and logs explore, if the first column is a float then it should be considered a timestamp with subsecond precision (similar to the UInt64 special case for Unix timestamps).

**Comment by oplehto** [comment]
Thining a bit further, the most versatile way would be the following: 
- The timestamp column should be obtained from the "Query Settings" tab if its set there
- The "Query Settings" timestamp selector should support also Float* and UInt64 based timestamps (this would also benefit timeseries and table panes)

**Comment by Slach** [comment]
@oplehto when use UInt64, shall we define how many right pad digits will use for fractional seconds? or just need to define 3 right digits always and use is as milliseconds?
