### ISSUE TITLE
Extrapolation applies not only to the numerical data.

### ISSUE THREAD

**Issue by antip00** [Altinity/clickhouse-grafana#640]
Extrapolation can be applied to strings, and we can get NaNs in the latest raw.
There no NaN in actual data and NaN exists only if extrapolation turned on. 

![Screenshot from 2024-10-15 17-19-13](https://github.com/user-attachments/assets/5ffbdf02-95bc-478c-827c-76caaf458681)
![Screenshot from 2024-10-15 17-29-56](https://github.com/user-attachments/assets/d21d4467-6590-4942-95e5-81dde0c19dcb)

**Comment by antip00** [comment]
![Screenshot from 2024-10-15 17-40-20](https://github.com/user-attachments/assets/0981086b-26d8-4e06-a1fd-36a6b7c0f63a)
Tried with other data types, extrapolation for other non-numerical types returns NaN, for NULL returns 0

**Comment by Slach** [comment]
actually if you have non-numeric data
it shall be series name
need more discuss in the next meeting
