### ISSUE TITLE
ad-hoc filters

### ISSUE THREAD

**Issue by curly3031** [Altinity/clickhouse-grafana#680]
In version 3.2.4 (2024-10-28)

ad-hoc filters not work on grafana 11.[1-3].0 in query

**Comment by curly3031** [comment]
version 3.2.3 work is fine

**Comment by Slach** [comment]
Check plugin 3.3.0 version, https://github.com/Altinity/clickhouse-grafana/releases/download/v3.3.0/vertamedia-clickhouse-datasource-3.3.0.zip

we already fixed it and waiting when Grafana labs publish our plugin
